controller_list:
  - name: fake_linear_controller
    joints:
      - x_move_joint
      - y_move_joint
      - z_move_joint
  - name: fake_arm_controller
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_joint
      - arm_wrist_1_joint
      - arm_wrist_2_joint
      - arm_wrist_3_joint
  - name: fake_endeffector_controller
    joints:
      []
initial:  # Define initial robot poses.
  - group: arm
    pose: home
