# gazebo_ros_control_params.yaml
gazebo_ros_control/pid_gains:
  x_move_joint: {p: 100.0, i: 0.0, d: 1.0}
  y_move_joint: {p: 100.0, i: 0.0, d: 1.0}
  z_move_joint: {p: 100.0, i: 0.0, d: 1.0}
  shoulder_pan_joint: {p: 1.0, i: 0.0, d: 1.0}
  shoulder_lift_joint: {p: 1.0, i: 0.0, d: 1.0}
  elbow_joint: {p: 1.0, i: 0.0, d: 1.0}
  wrist_1_joint: {p: 1.0, i: 0.0, d: 1.0}
  wrist_2_joint: {p: 1.0, i: 0.0, d: 1.0}
  wrist_3_joint: {p: 1.0, i: 0.0, d: 1.0}
